//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EconomySim.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("EconomySim.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {
        ///	&quot;start_conditions&quot;:{
        ///		&quot;agents&quot;:{
        ///			&quot;farmer&quot;:10,
        ///			&quot;miner&quot;:10,
        ///			&quot;woodcutter&quot;:10,
        ///			&quot;refiner&quot;:10,
        ///			&quot;blacksmith&quot;:10
        ///		}
        ///	},
        ///	&quot;goods&quot;:[
        ///		{&quot;id&quot;:&quot;food&quot; ,&quot;size&quot;:&quot;0.5&quot;},
        ///		{&quot;id&quot;:&quot;wood&quot; ,&quot;size&quot;:&quot;1.0&quot;},
        ///		{&quot;id&quot;:&quot;ore&quot;  ,&quot;size&quot;:&quot;1.0&quot;},
        ///		{&quot;id&quot;:&quot;metal&quot;,&quot;size&quot;:&quot;1.0&quot;},
        ///		{&quot;id&quot;:&quot;tools&quot;,&quot;size&quot;:&quot;1.0&quot;}
        ///	],
        ///	&quot;agents&quot;:[
        ///		{
        ///			&quot;id&quot;:&quot;farmer&quot;,
        ///			&quot;money&quot;:100,
        ///			&quot;inventory&quot;:{
        ///				&quot;start&quot;:{&quot;food&quot;:0,&quot;tools&quot;:1,&quot;wood&quot;:0},
        ///				&quot;ideal&quot;:{&quot;food&quot;:0,&quot;tools&quot;:1,&quot;wood&quot;:3},
        ///				&quot;max_size&quot;:20
        ///			},
        ///			&quot;logi [rest of string was truncated]&quot;;.
        /// </summary>
        public static string settings_json {
            get {
                return ResourceManager.GetString("settings_json", resourceCulture);
            }
        }
    }
}
